#include "Input/keyMapping.h"

namespace input {
    std::unordered_map<int, KeyboardInput> keyMapping = {
        // Litery
        {GLFW_KEY_A, KEY_A}, {GLFW_KEY_B, KEY_B}, {GLFW_KEY_C, KEY_C}, {GLFW_KEY_D, KEY_D},
        {GLFW_KEY_E, KEY_E}, {GLFW_KEY_F, KEY_F}, {GLFW_KEY_G, KEY_G}, {GLFW_KEY_H, KEY_H},
        {GLFW_KEY_I, KEY_I}, {GLFW_KEY_J, KEY_J}, {GLFW_KEY_K, KEY_K}, {GLFW_KEY_L, KEY_L},
        {GLFW_KEY_M, KEY_M}, {GLFW_KEY_N, KEY_N}, {GLFW_KEY_O, KEY_O}, {GLFW_KEY_P, KEY_P},
        {GLFW_KEY_Q, KEY_Q}, {GLFW_KEY_R, KEY_R}, {GLFW_KEY_S, KEY_S}, {GLFW_KEY_T, KEY_T},
        {GLFW_KEY_U, KEY_U}, {GLFW_KEY_V, KEY_V}, {GLFW_KEY_W, KEY_W}, {GLFW_KEY_X, KEY_X},
        {GLFW_KEY_Y, KEY_Y}, {GLFW_KEY_Z, KEY_Z},

        // Cyfry
        {GLFW_KEY_0, KEY_0}, {GLFW_KEY_1, KEY_1}, {GLFW_KEY_2, KEY_2}, {GLFW_KEY_3, KEY_3},
        {GLFW_KEY_4, KEY_4}, {GLFW_KEY_5, KEY_5}, {GLFW_KEY_6, KEY_6}, {GLFW_KEY_7, KEY_7},
        {GLFW_KEY_8, KEY_8}, {GLFW_KEY_9, KEY_9},

        // Klawisze funkcyjne
        {GLFW_KEY_F1, KEY_F1}, {GLFW_KEY_F2, KEY_F2}, {GLFW_KEY_F3, KEY_F3}, {GLFW_KEY_F4, KEY_F4},
        {GLFW_KEY_F5, KEY_F5}, {GLFW_KEY_F6, KEY_F6}, {GLFW_KEY_F7, KEY_F7}, {GLFW_KEY_F8, KEY_F8},
        {GLFW_KEY_F9, KEY_F9}, {GLFW_KEY_F10, KEY_F10}, {GLFW_KEY_F11, KEY_F11}, {GLFW_KEY_F12, KEY_F12},

        // Znaki specjalne
        {GLFW_KEY_COMMA, KEY_COMMA}, {GLFW_KEY_PERIOD, KEY_PERIOD}, {GLFW_KEY_SLASH, KEY_SLASH},
        {GLFW_KEY_SEMICOLON, KEY_SEMICOLON}, {GLFW_KEY_APOSTROPHE, KEY_QUOTE},
        {GLFW_KEY_LEFT_BRACKET, KEY_BRACKET_OPEN}, {GLFW_KEY_RIGHT_BRACKET, KEY_BRACKET_CLOSE},
        {GLFW_KEY_BACKSLASH, KEY_BACKSLASH},

        // Klawisze specjalne
        {GLFW_KEY_SPACE, KEY_SPACE}, {GLFW_KEY_TAB, KEY_TAB}, {GLFW_KEY_ENTER, KEY_ENTER},
        {GLFW_KEY_BACKSPACE, KEY_BACKSPACE}, {GLFW_KEY_ESCAPE, KEY_ESC},
        {GLFW_KEY_LEFT_SHIFT, KEY_SHIFT}, {GLFW_KEY_LEFT_CONTROL, KEY_CTRL}, {GLFW_KEY_LEFT_ALT, KEY_ALT},
        {GLFW_KEY_RIGHT_SHIFT, KEY_SHIFT}, {GLFW_KEY_RIGHT_CONTROL, KEY_CTRL}, {GLFW_KEY_RIGHT_ALT, KEY_ALT}
    };


    std::unordered_map<int, MouseInput> mouseMapping = {
    {GLFW_MOUSE_BUTTON_LEFT, MOUSE_LEFT},
    {GLFW_MOUSE_BUTTON_RIGHT, MOUSE_RIGHT},
    {GLFW_MOUSE_BUTTON_MIDDLE, MOUSE_MIDDLE},
    {GLFW_MOUSE_BUTTON_4, MOUSE_EXTRA1},
    {GLFW_MOUSE_BUTTON_5, MOUSE_EXTRA2}
    };
}